[book]
authors = ["Ville Sundell / Solarius Intellectual Properties Ky"]
language = "en"
multilingual = false
src = "src"
title = "Move Patterns: Design Patterns for Resource Based Programming"
description = "Book on software design patterns for Move smart contract programming language."

[output.html]
git-repository-url = "https://github.com/chrisyy2003/move-patterns"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/chrisyy2003/move-patterns/edit/main/{path}"
cname = "move-patterns.chrisyy.top"